server:
  port: ${port}
spring:
  application:
    name: service    # 项目名称尽量用小写
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: chenzhen
#    password: 33
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eurekaregister:8081/eureka/,http://eurekaregister:8082/eureka/
      defaultZone: http://eurekaregister:8081/eureka/
  instance:
    hostname: eurekaServer  # 指定该Eureka实例的主机名
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}
